language: java

jdk: openjdk8

env:
   global:
      - ACTIVE_PROFILES="-Pjacoco" ADDITIONAL_MAVEN_ARGS="sonar:sonar"
   
addons:
   sonarcloud:
      organization: "alessandroarezzo-github"
      token: $SONAR_TOKEN

install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache
      
script:
    - mvn -f budget-management/pom.xml $ACTIVE_PROFILES clean verify $ADDITIONAL_MAVEN_ARGS