language: java

dist: xenial

jdk: openjdk8

services:
   - xvbf
   - docker
   
env:
   global:
      - ACTIVE_PROFILES="-Pjacoco,mutation-testing" ADDITIONAL_MAVEN_ARGS="coveralls:report sonar:sonar"
   
addons:
   sonarcloud:
      organization: "alessandroarezzo-github"
      token: $SONAR_TOKEN

install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache
      
script:
    - mvn -f budget-management/pom.xml $ACTIVE_PROFILES clean verify $ADDITIONAL_MAVEN_ARGS